-- MySQL Script generated by MySQL Workbench
-- Mon 14 Jan 2019 05:13:44 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema abp32
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `abp32` ;

-- -----------------------------------------------------
-- Schema abp32
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abp32` ;
USE `abp32` ;

-- -----------------------------------------------------
-- Table `abp32`.`Usuario_Registrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Usuario_Registrado` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Usuario_Registrado` (
  `userId` VARCHAR(20) NOT NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `abp32`.`Usuario_Registrado` (`email` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Administrador` (
  `userId` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_Administrador_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Usuario_Registrado` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abp32`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Partido` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Partido` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `idPista` INT NULL,
  `horario` DATETIME NOT NULL,
  PRIMARY KEY (`idPartido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abp32`.`Pista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Pista` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Pista` (
  `idPista` INT NOT NULL AUTO_INCREMENT,
  `tipoSuelo` VARCHAR(20) NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idPista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abp32`.`Deportista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Deportista` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Deportista` (
  `userId` VARCHAR(20) NOT NULL,
  `isSocio` TINYINT NOT NULL,
  `nivel` TINYINT(2) NULL,
  `genero` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_Deportista_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Usuario_Registrado` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abp32`.`Deportistas_Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Deportistas_Partido` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Deportistas_Partido` (
  `idPartido` INT NOT NULL,
  `userId` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPartido`, `userId`),
  CONSTRAINT `fk_Deportistas_Partido_idPartido`
    FOREIGN KEY (`idPartido`)
    REFERENCES `abp32`.`Partido` (`idPartido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Deportistas_Partido_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Deportista` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `userId_idx` ON `abp32`.`Deportistas_Partido` (`userId` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `genero` VARCHAR(2) NULL,
  `nivel` TINYINT(2) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abp32`.`Campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Campeonato` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Campeonato` (
  `idCampeonato` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `maxParticipantes` SMALLINT(4) NULL,
  `normativa` VARCHAR(100) NOT NULL,
  `fechaLimite` DATETIME NOT NULL,
  PRIMARY KEY (`idCampeonato`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `abp32`.`Campeonato` (`nombre` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Categorias_Campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Categorias_Campeonato` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Categorias_Campeonato` (
  `idCategoria` INT NOT NULL,
  `idCampeonato` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `idCampeonato`),
  CONSTRAINT `fk_Categorias_Campeonato_idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `abp32`.`Categoria` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Categorias_Campeonato_idCampeonato`
    FOREIGN KEY (`idCampeonato`)
    REFERENCES `abp32`.`Campeonato` (`idCampeonato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Categorias_Campeonato_idCampeonato_idx` ON `abp32`.`Categorias_Campeonato` (`idCampeonato` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `idCampeonato` INT NOT NULL,
  PRIMARY KEY (`idGrupo`),
  CONSTRAINT `fk_Grupo_idCategoria`
    FOREIGN KEY (`idCategoria` , `idCampeonato`)
    REFERENCES `abp32`.`Categorias_Campeonato` (`idCategoria` , `idCampeonato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Grupo_idCategoria_idx` ON `abp32`.`Grupo` (`idCategoria` ASC, `idCampeonato` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Pareja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Pareja` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Pareja` (
  `idPareja` INT NOT NULL AUTO_INCREMENT,
  `capitan` VARCHAR(20) NULL DEFAULT NULL,
  `par` VARCHAR(20) NULL DEFAULT NULL,
  `idGrupo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPareja`),
  CONSTRAINT `fk_Pareja_capitan`
    FOREIGN KEY (`capitan`)
    REFERENCES `abp32`.`Deportista` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pareja_grupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `abp32`.`Grupo` (`idGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pareja_par`
    FOREIGN KEY (`par`)
    REFERENCES `abp32`.`Deportista` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Pareja_capitan_idx` ON `abp32`.`Pareja` (`capitan` ASC) ;

CREATE INDEX `fk_Pareja_grupo_idx` ON `abp32`.`Pareja` (`idGrupo` ASC) ;

CREATE INDEX `fk_Pareja_par_idx` ON `abp32`.`Pareja` (`par` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Parejas_Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Parejas_Grupo` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Parejas_Grupo` (
  `idGrupo` INT NOT NULL,
  `idPareja` INT NOT NULL,
  PRIMARY KEY (`idGrupo`, `idPareja`),
  CONSTRAINT `fk_Parejas_Grupo_idGrupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `abp32`.`Grupo` (`idGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Parejas_Grupo_idPareja`
    FOREIGN KEY (`idPareja`)
    REFERENCES `abp32`.`Pareja` (`idPareja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `idGrupo_idx` ON `abp32`.`Parejas_Grupo` (`idGrupo` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Enfrentamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Enfrentamiento` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Enfrentamiento` (
  `idEnfrentamiento` INT NOT NULL AUTO_INCREMENT,
  `resultado` VARCHAR(11) NULL,
  `idPareja1` INT NOT NULL,
  `idPareja2` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idPista` INT NULL,
  `horario` DATETIME NULL,
  `ganador` INT NULL,
  `ronda` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idEnfrentamiento`),
  CONSTRAINT `fk_Enfrentamiento_idPareja1`
    FOREIGN KEY (`idPareja1`)
    REFERENCES `abp32`.`Parejas_Grupo` (`idPareja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Enfrentamiento_idGrupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `abp32`.`Grupo` (`idGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Enfrentamiento_idPista`
    FOREIGN KEY (`idPista`)
    REFERENCES `abp32`.`Pista` (`idPista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `idGrupo_idx` ON `abp32`.`Enfrentamiento` (`idGrupo` ASC) ;

CREATE INDEX `idPista_idx` ON `abp32`.`Enfrentamiento` (`idPista` ASC) ;

CREATE INDEX `idPareja_idx` ON `abp32`.`Enfrentamiento` (`idPareja1` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Parejas_Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Parejas_Categoria` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Parejas_Categoria` (
  `idPareja` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idCampeonato` INT NOT NULL,
  PRIMARY KEY (`idPareja`, `idCategoria`),
  CONSTRAINT `fk_Parejas_Categoria_idPareja`
    FOREIGN KEY (`idPareja`)
    REFERENCES `abp32`.`Pareja` (`idPareja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parejas_Categoria_idCategoria`
    FOREIGN KEY (`idCategoria` , `idCampeonato`)
    REFERENCES `abp32`.`Categorias_Campeonato` (`idCategoria` , `idCampeonato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPareja_UNIQUE` ON `abp32`.`Parejas_Categoria` (`idPareja` ASC) ;

CREATE INDEX `fk_Parejas_Categoria_idCategoria_idx` ON `abp32`.`Parejas_Categoria` (`idCategoria` ASC, `idCampeonato` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Entrenador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Entrenador` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Entrenador` (
  `userId` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_Entrenador_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Usuario_Registrado` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abp32`.`Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Clase` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Clase` (
  `idClase` INT NOT NULL AUTO_INCREMENT,
  `nivel` TINYINT(2) NOT NULL,
  `creador` VARCHAR(20) NULL,
  `idEntrenador` VARCHAR(20) NOT NULL,
  `horario` DATETIME NOT NULL,
  PRIMARY KEY (`idClase`),
  CONSTRAINT `fk_Clase_creador`
    FOREIGN KEY (`creador`)
    REFERENCES `abp32`.`Usuario_Registrado` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_entrenador`
    FOREIGN KEY (`idEntrenador`)
    REFERENCES `abp32`.`Entrenador` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Clase_entrenador_idx` ON `abp32`.`Clase` (`idEntrenador` ASC) ;

CREATE INDEX `fk_Clase_creador_idx` ON `abp32`.`Clase` (`creador` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Calendario` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Calendario` (
  `idCalendario` INT NOT NULL AUTO_INCREMENT,
  `FechaHoraInicio` DATETIME NOT NULL,
  `FechaHoraFin` DATETIME NOT NULL,
  `idPista` INT NOT NULL,
  `userId` VARCHAR(20) NULL,
  `tipoReserva` VARCHAR(20) NULL,
  PRIMARY KEY (`idCalendario`),
  CONSTRAINT `fk_Calendario_idPista`
    FOREIGN KEY (`idPista`)
    REFERENCES `abp32`.`Pista` (`idPista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Calendario_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Usuario_Registrado` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Calendario_userId_idx` ON `abp32`.`Calendario` (`userId` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Calendario_Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Calendario_Clase` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Calendario_Clase` (
  `idClase` INT NOT NULL,
  `idCalendario` INT NOT NULL,
  PRIMARY KEY (`idClase`, `idCalendario`),
  CONSTRAINT `fk_Calendario_Clase_IdClase`
    FOREIGN KEY (`idClase`)
    REFERENCES `abp32`.`Clase` (`idClase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Calendario_Clase_IdCalendario`
    FOREIGN KEY (`idCalendario`)
    REFERENCES `abp32`.`Calendario` (`idCalendario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Calendario_Clase_HoraInicio_idx` ON `abp32`.`Calendario_Clase` (`idCalendario` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Asistencia` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Asistencia` (
  `userId` VARCHAR(20) NOT NULL,
  `idClase` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `control` TINYINT(1) NULL,
  PRIMARY KEY (`userId`, `idClase`, `fecha`),
  CONSTRAINT `fk_Asistencia_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Deportista` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Asistencia_idClase`
    FOREIGN KEY (`idClase`)
    REFERENCES `abp32`.`Clase` (`idClase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Deportistas_Clase_idClase_idx` ON `abp32`.`Asistencia` (`idClase` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`FechasPreseleccionadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`FechasPreseleccionadas` ;

CREATE TABLE IF NOT EXISTS `abp32`.`FechasPreseleccionadas` (
  `fecha` DATETIME NOT NULL,
  `idEnfrentamiento` INT NOT NULL,
  PRIMARY KEY (`fecha`, `idEnfrentamiento`),
  CONSTRAINT `fk_FechasPreseleccionadas_idEnfrentamient`
    FOREIGN KEY (`idEnfrentamiento`)
    REFERENCES `abp32`.`Enfrentamiento` (`idEnfrentamiento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_FechasPreseleccionadas_idEnfrentamient_idx` ON `abp32`.`FechasPreseleccionadas` (`idEnfrentamiento` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(20) NOT NULL,
  `mensaje` VARCHAR(280) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idMensaje`),
  CONSTRAINT `fk_Message_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Deportista` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Message_userId_idx` ON `abp32`.`Mensaje` (`userId` ASC) ;


-- -----------------------------------------------------
-- Table `abp32`.`Deportistas_Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abp32`.`Deportistas_Clase` ;

CREATE TABLE IF NOT EXISTS `abp32`.`Deportistas_Clase` (
  `userId` VARCHAR(20) NOT NULL,
  `idClase` INT NOT NULL,
  PRIMARY KEY (`userId`, `idClase`),
  CONSTRAINT `fk_Deportistas_Clase_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `abp32`.`Deportista` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deportistas_Clase_idClase`
    FOREIGN KEY (`idClase`)
    REFERENCES `abp32`.`Clase` (`idClase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Deportistas_Clase_classId_idx` ON `abp32`.`Deportistas_Clase` (`idClase` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
